import type { QRTypeConfig } from '../types';

export const QR_TYPES: QRTypeConfig[] = [
  {
    id: 'website',
    label: 'Website',
    description: 'Share any URL or web page',
    icon: 'globe',
    category: 'business',
  },
  {
    id: 'text',
    label: 'Text',
    description: 'Encode plain text content',
    icon: 'type',
    category: 'content',
  },
  {
    id: 'wifi',
    label: 'Wi-Fi',
    description: 'Quick Wi-Fi network access',
    icon: 'wifi',
    category: 'connectivity',
  },
  {
    id: 'whatsapp',
    label: 'WhatsApp',
    description: 'Start a WhatsApp conversation',
    icon: 'message-circle',
    category: 'connectivity',
  },
  {
    id: 'phone',
    label: 'Phone',
    description: 'Dial a phone number',
    icon: 'phone',
    category: 'connectivity',
  },
  {
    id: 'sms',
    label: 'SMS',
    description: 'Send a text message',
    icon: 'message-square',
    category: 'connectivity',
  },
  {
    id: 'email',
    label: 'Email',
    description: 'Compose an email',
    icon: 'mail',
    category: 'connectivity',
  },
  {
    id: 'contact',
    label: 'Contact',
    description: 'Share contact details',
    icon: 'user',
    category: 'business',
  },
  {
    id: 'location',
    label: 'Location',
    description: 'Share a geographic location',
    icon: 'map-pin',
    category: 'business',
  },
  {
    id: 'event',
    label: 'Event',
    description: 'Calendar event details',
    icon: 'calendar',
    category: 'marketing',
  },
  {
    id: 'social',
    label: 'Social',
    description: 'Social media profile link',
    icon: 'share-2',
    category: 'marketing',
  },
  {
    id: 'custom',
    label: 'Custom',
    description: 'Any text or data',
    icon: 'code',
    category: 'content',
  },
  {
    id: 'upload',
    label: 'Upload',
    description: 'Upload image, PDF or file to encode',
    icon: 'upload',
    category: 'uploads',
  },
  {
    id: 'mpesa',
    label: 'M-PESA',
    description: 'Accept M-PESA payments with a scan',
    icon: 'smartphone',
    category: 'payments',
  },
  {
    id: 'mpesa-till',
    label: 'M-PESA Till',
    description: 'Buy Goods / Till number payments',
    icon: 'store',
    category: 'payments',
  },
  {
    id: 'mpesa-paybill',
    label: 'PayBill',
    description: 'M-PESA PayBill payments',
    icon: 'receipt',
    category: 'payments',
  },
  {
    id: 'mpesa-send',
    label: 'Send Money',
    description: 'M-PESA Send Money QR code',
    icon: 'send',
    category: 'payments',
  },
  {
    id: 'bank-payment',
    label: 'Bank Payment',
    description: 'Kenyan bank payment details',
    icon: 'landmark',
    category: 'payments',
  },
  {
    id: 'payment-link',
    label: 'Payment Link',
    description: 'Link to your online payment page',
    icon: 'link',
    category: 'payments',
  },
];
