import { useState } from 'react';
import { ChevronDown } from 'lucide-react';
import kenyaImage from '../assets/kenya.jpg';

const faqs = [
  {
    question: 'What is a QR code?',
    answer: 'A QR code (Quick Response code) is a type of barcode that can be scanned by a smartphone camera to quickly access information such as a website, payment details, contact information, or Wi-Fi credentials.',
  },
  {
    question: 'How does Kenya QR work?',
    answer: 'Kenya QR lets you create QR codes entirely in your browser. Choose a QR type, enter your information, and generate a downloadable QR code. No data is sent to any server — everything stays on your device.',
  },
  {
    question: 'Can I create an M-PESA QR code?',
    answer: 'Yes. Kenya QR supports M-PESA payment QR codes including Till/Buy Goods, PayBill, and Send Money. The QR code encodes the payment information that customers can use to complete their payment.',
  },
  {
    question: 'Can I create a PayBill QR code?',
    answer: 'Yes. You can create a PayBill QR code by entering your business name, PayBill number, optional account number, amount, and reference. The QR code will contain this payment information.',
  },
  {
    question: 'Can I create a Till number QR code?',
    answer: 'Yes. Kenya QR supports Till/Buy Goods number QR codes. Enter your business name, till number, optional amount, and reference to generate a QR code for your customers to scan.',
  },
  {
    question: 'Do QR codes expire?',
    answer: 'The QR codes generated by Kenya QR do not expire. However, if your QR code encodes a URL, the link validity depends on the website it points to. Static QR codes remain scannable permanently.',
  },
  {
    question: 'Can I customize my QR code?',
    answer: 'Yes. You can customize the foreground color, background color, size, margin, error correction level, and even add a center logo to your QR code.',
  },
  {
    question: 'Can I download my QR code?',
    answer: 'Yes. You can download your QR code as a PNG or SVG file, or print it directly. PNG files are generated at 3x resolution for crisp, high-quality output.',
  },
  {
    question: 'Can I use QR codes for my business?',
    answer: 'Absolutely. QR codes are perfect for businesses of all sizes — from restaurants and retail stores to professionals and events. Share menus, payment details, contact information, and more.',
  },
  {
    question: 'Can I use QR codes on printed materials?',
    answer: 'Yes. QR codes work great on printed materials like business cards, posters, flyers, receipts, product packaging, and event tickets. Download as SVG for the best print quality.',
  },
  {
    question: 'Does Kenya QR store my payment information?',
    answer: 'No. Kenya QR does not store, transmit, or have access to any of your data. The QR code is generated entirely in your browser and no information is sent to any server.',
  },
  {
    question: 'Can I scan a Kenya QR code using my phone?',
    answer: 'Yes. Any smartphone with a camera can scan Kenya QR codes. Most modern phones have a built-in QR scanner in the camera app, or you can use any free QR scanner app.',
  },
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section id="faq" className="py-16 sm:py-24 bg-white border-y border-border">
      <div className="max-w-[1100px] mx-auto px-5 sm:px-6">
        <div className="text-center mb-12">
          <span className="inline-block text-[11px] font-semibold text-accent uppercase tracking-widest mb-3">FAQ</span>
          <h2 className="text-[26px] sm:text-[32px] md:text-[36px] font-bold text-text-dark tracking-tight">
            Frequently Asked Questions
          </h2>
          <p className="mt-3 text-[15px] text-text-muted max-w-lg mx-auto">
            Everything you need to know about Kenya QR.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-[1fr_520px] gap-6 items-start">
          <div className="space-y-2">
            {faqs.map((faq, index) => (
              <div
                key={index}
                className="bg-surface rounded-2xl border border-border overflow-hidden transition-all duration-300"
              >
                <button
                  onClick={() => setOpenIndex(openIndex === index ? null : index)}
                  className="w-full flex items-center justify-between gap-4 px-5 py-4 text-left"
                  aria-expanded={openIndex === index}
                >
                  <span className="text-[14px] font-medium text-text-dark pr-4">{faq.question}</span>
                  <ChevronDown
                    size={18}
                    className={`text-text-muted flex-shrink-0 transition-transform duration-300 ${
                      openIndex === index ? 'rotate-180 text-accent' : ''
                    }`}
                  />
                </button>
                <div
                  className={`overflow-hidden transition-all duration-300 ${
                    openIndex === index ? 'max-h-[300px] opacity-100' : 'max-h-0 opacity-0'
                  }`}
                >
                  <div className="px-5 pb-4 pt-0">
                    <p className="text-[13px] text-text-muted leading-relaxed">{faq.answer}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Right: Kenya Image */}
          <div className="hidden lg:flex justify-end mt-40">
            <img
              src={kenyaImage}
              alt="Kenya"
              className="w-full rounded-3xl object-cover shadow-lg border border-border/60"
            />
          </div>
        </div>
      </div>
    </section>
  );
}
